name: aaaa


data:
  root: /store
  train_annotaion: train.csv
  train_image_dir: train

checkpoint:
  _target_: python.lighting.callbacks.ModelCheckpoint
  monitor: score
  filename: "sample-mnist-{epoch:02d}-{val_loss:.2f}",


train:
  default_root_dir: /store/checkpoints

loader:
  train:
    batch_size: 16
    num_workers: 6
