version: '2.4'

services:
  app:
    tty: true
    image: "cellseg"
    build: 
      context: .
    shm_size: '30gb'
    volumes:
      - .:/app
      - ./store:/store
      - ./.cache:/root/.cache
    environment:
      KAGGLE_USERNAME: ${KAGGLE_USERNAME:?}
      KAGGLE_KEY: ${KAGGLE_KEY:?}
      CUDA_VISIBLE_DEVICES:
