version: 2

jobs:
  build_and_test:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-1604-cuda-10.2:202012-01
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: "Setup environment variables"
          command: |
            echo 'export COMPOSE_FILE=docker-compose.yml' >> $BASH_ENV
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: "Build images"
          command: |
            docker-compose build
      - run:
          name: "test"
          command: |
            docker-compose run --rm app pytest
            

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
