name: center-baseline
use_amp: true
num_epochs: 100
device: cuda
seed: &seed 0 
log_keys:
  - loss
  - category_loss
  - mask_loss


root_path: &root_path /store
data:
  root_path: *root_path
  train_file_path: /store/train.csv
  train_images_path: /store/train
  cell_types:
    - shsy5y 
    - astro 
    - cort

num_classes: &num_classes 1
original_size: 512
box_size: &box_size 64
fold:
  index: 0
  n_splits: 6
  seed: *seed

backbone:
  name: "efficientnet-b1"

model:
  category_feat_range: [0, 6]
  hidden_channels: 64
  num_classes: *num_classes
  box_size: *box_size


mask_ap:
  reduce_size: 1
  use_batch: true


to_masks:
  category_threshold: 0.5
  mask_threshold: 0.85

dataset:
  img_dir: /store/train
  train_csv: /store/train.csv
criterion:
  category_weight: 0.7
  mask_weight: 1.3
  box_size: *box_size

optimizer:
  lr: 1e-4

train_loader:
  batch_size: 6 
  shuffle: true
  num_workers: 5

validation_loader:
  batch_size: 5
  shuffle: false
  num_workers: 6
