name: solo-baseline-patch-b0-16-64
use_amp: true
num_epochs: 100
device: cuda
seed: &seed 0 
log_keys:
  - loss
  - category_loss
  - mask_loss



root_path: &root_path /store


data:
  root_path: *root_path
  train_file_path: /store/train.csv
  train_images_path: /store/train
  cell_types:
    - shsy5y 
    - astro 
    - cort

num_classes: 1
patch_size: 128
fold:
  index: 0
  n_splits: 6
  seed: *seed

backbone:
  name: "efficientnet-b0"

model:
  grid_size: 16
  category_feat_range: [3, 6]
  mask_feat_range: [0, 4]
  hidden_channels: 64

mask_ap:
  reduce_size: 1
  use_batch: true


to_masks:
  category_threshold: 0.7
  mask_threshold: 0.7
  kernel_size: 3
  use_nms: false

dataset:
  img_dir: /store/train
  train_csv: /store/train.csv
  smallest_area: 36

criterion:
  category_weight: 1.0
  mask_weight: 1.0

optimizer:
  lr: 5e-4

scheduler:
  mode: min
  factor: 0.5
  patience: 10
  threshold: 0.0001
  threshold_mode: abs

train_loader:
  batch_size: 32
  shuffle: true
  num_workers: 4
  drop_last: true

validation_loader:
  batch_size: 32
  shuffle: false
  num_workers: 4
