name: solo-baseline-patch-slim
use_amp: true
num_epochs: 100
device: cuda
seed: &seed 0 
log_keys:
  - loss
  - category_loss
  - mask_loss



root_path: &root_path /store
data:
  root_path: *root_path
  train_file_path: /store/train.csv
  train_images_path: /store/train
  cell_types:
    - shsy5y 
    - astro 
    - cort

num_classes: 1
original_size: 128
patch_size: 128
fold:
  index: 0
  n_splits: 6
  seed: *seed

backbone:
  name: "efficientnet-b3"

model:
  grid_size: 16
  category_feat_range: [3, 6]
  mask_feat_range: [0, 6]
  hidden_channels: 128

mask_ap:
  reduce_size: 8
  use_batch: true
  thresholds:
    - 0.7


to_masks:
  category_threshold: 0.6
  mask_threshold: 0.85
  kernel_size: 3
  use_nms: false

dataset:
  img_dir: /store/train
  train_csv: /store/train.csv
criterion:
  category_weight: 1.0
  mask_weight: 5.0

optimizer:
  lr: 1e-4

train_loader:
  batch_size: 16
  shuffle: true
  num_workers: 4

validation_loader:
  batch_size: 16
  shuffle: false
  num_workers: 4
