
name: solo-baseline
gpus: 1
mixed_presision: false
num_epochs: 100
device: cuda

num_classes: 1
original_size: 480
fold:
  index: 0
  n_splits: 5
  seed: 0

backbone:
  name: "efficientnet-b2"

model:
  grid_size: 60
  category_feat_range: [2, 6]
  mask_feat_range: [0, 4]
  hidden_channels: 64

dataset:
  img_dir: /store/train
  train_csv: /store/train.csv


optimizer:
  lr: &lr 1.0e-2
  momentum: 0.95
  nesterov: true

train_loader:
  batch_size: 2 
  shuffle: true
  num_workers: 6

validation_loader:
  batch_size: 16
  shuffle: false
  num_workers: 6


# dataset:
#   image:
#     size: 512
#     channels: 3
#   num_classes: 1
