name: solo-baseline
mixed_presision: true
num_epochs: 100
device: cuda
seed: &seed 0 

data:
  root_path: /store
  train_file_path: /store/train.csv
  train_images_path: /store/train
  cell_types:
    - shsy5y 
    - astro
    - cort
num_classes: 1
original_size: 384
fold:
  index: 0
  n_splits: 5
  seed: *seed

backbone:
  name: "efficientnet-b2"

model:
  grid_size: 50
  category_feat_range: [2, 5]
  mask_feat_range: [0, 3]
  hidden_channels: 64

dataset:
  img_dir: /store/train
  train_csv: /store/train.csv


optimizer:
  lr: &lr 1.0e-2
  momentum: 0.95
  nesterov: true

train_loader:
  batch_size: 4 
  shuffle: true
  num_workers: 6

validation_loader:
  batch_size: 4
  shuffle: false
  num_workers: 6
