name: mask_yolo-test
use_amp: true
num_epochs: 100
device: cuda
seed: &seed 0 
log_keys:
  - loss
  - obj_loss
  - box_loss
  - local_mask_loss

root_path: &root_path /store

num_classes: 1
patch_size: 768
mask_size: 8

# model
box_feat_range: [3, 6]
mask_feat_range: [0, 4]
hidden_channels: 64
score_threshold: 0.5
box_iou_threshold: 0.5
mask_threshold: 0.5


# to masks
use_global_mask: true

data:
  root_path: *root_path
  train_file_path: /store/train.csv
  train_images_path: /store/train
  cell_types:
    - shsy5y 
    - astro 
    - cort

fold:
  index: 0
  n_splits: 6
  seed: *seed

backbone:
  name: "efficientnet-b0"

mask_ap:
  reduce_size: 8
  use_batch: true
  # thresholds:
  #   - 0.7


dataset:
  img_dir: /store/train
  train_csv: /store/train.csv
  smallest_area: 8

criterion:
  obj_weight: 5.0
  box_weight: 0.5
  cate_weight: 0.0
  local_mask_weight: 0.5
  assign_topk: 19

optimizer:
  lr: 1e-3
  # lr: 5e-4

scheduler:
  mode: min
  factor: 0.5
  patience: 10
  threshold: 0.0001
  threshold_mode: abs

train_loader:
  batch_size: 4
  shuffle: true
  num_workers: 3
  drop_last: true

validation_loader:
  batch_size: 4
  shuffle: false
  num_workers: 3
