name: mask_yolo-b2-512-4-6-32
use_amp: true
use_patch: false
num_epochs: 100
device: cuda
seed: &seed 0 
log_keys:
  - loss
  - obj_loss
  - box_loss
  - local_mask_loss

root_path: &root_path /store

num_classes: 1
patch_size: 704
mask_size: 32

# model
box_feat_range: [4, 6]
mask_feat_range: [0, 2]
hidden_channels: 64
score_threshold: 0.5
box_iou_threshold: 0.4
mask_threshold: 0.4

data:
  root_path: *root_path
  train_file_path: /store/train.csv
  train_images_path: /store/train
  cell_types:
    - shsy5y 
    - astro 
    - cort

fold:
  index: 0
  n_splits: 5
  seed: *seed

backbone:
  name: "efficientnet-b2"

mask_ap:
  reduce_size: 4

dataset:
  img_dir: /store/train
  train_csv: /store/train.csv
  smallest_area: 8

criterion:
  obj_weight: 2.0
  box_weight: 1.0
  cate_weight: 0.0
  local_mask_weight: 0.2

assign:
  topk: 10
  radius: 2.5
  center_weight: 0.5
  obj_weight: 2.0
  box_weight: 1.0

optimizer:
  lr: &lr 1.0e-3
  # lr: &lr 5.0e-4
  # lr: &lr 1.0e-4

scheduler:
  mode: min
  factor: 0.5
  patience: 10
  threshold: 0.0001
  threshold_mode: abs

train_loader:
  batch_size: 3
  shuffle: true
  num_workers: 3
  drop_last: true

validation_loader:
  batch_size: 3
  shuffle: false
  num_workers: 3
