name: mask_yolo-test
use_amp: true
num_epochs: 100
device: cuda
seed: &seed 0 
log_keys:
  - loss
  - category_loss
  - size_loss
  - offset_loss
  - mask_loss
  - sliency_loss

root_path: &root_path /store

num_classes: 1
patch_size: 768
grid_size: 48
mask_size: 8

# model
box_feat_range: [2, 6]
mask_feat_range: [0, 6]
hidden_channels: 128


# to masks
category_threshold: 0.6
mask_threshold: 0.4
use_global_mask: true

data:
  root_path: *root_path
  train_file_path: /store/train.csv
  train_images_path: /store/train
  cell_types:
    - shsy5y 
    - astro 
    - cort

fold:
  index: 0
  n_splits: 6
  seed: *seed

backbone:
  name: "efficientnet-b0"

mask_ap:
  reduce_size: 8
  use_batch: true
  # thresholds:
  #   - 0.7


dataset:
  img_dir: /store/train
  train_csv: /store/train.csv
  smallest_area: 8
criterion:
  obj_weight: 1.0
  box_weight: 1.0
  cate_weight: 1.0
  local_mask_weight: 1.0

optimizer:
  lr: 1e-3
  # lr: 5e-4

scheduler:
  mode: min
  factor: 0.5
  patience: 10
  threshold: 0.0001
  threshold_mode: abs

train_loader:
  batch_size: 5
  shuffle: true
  num_workers: 4
  drop_last: true

validation_loader:
  batch_size: 5
  shuffle: false
  num_workers: 4
